export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';

export const GET_REPO_REQUEST = 'GET_REPO_REQUEST';

export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';

export const GET_REPO_FAILURE = 'GET_REPO_FAILURE';

export const CLEAR_REPOS = 'CLEAR_REPOS';